# BASE DE DATOS
spring.datasource.url=jdbc:sqlserver://localhost\\SQLEXPRESS;databaseName=Emerson_jr;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa_spring
spring.datasource.password=Spring2026*
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA / HIBERNATE
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update