# BASE DE DATOS
spring.datasource.url=jdbc:mysql://localhost:3306/donaciones26
spring.datasource.username=banco
spring.datasource.password=Banco2026!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / HIBERNATE

spring.jpa.database=mysql
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true

#hace que las tablas se creen solas en mysql, si no existe la base de datos, se crea automaticamente    
spring.jpa.hibernate.ddl-auto=update

